name: ByteMotion AB NodeJS CI - Build, Test, and Publish

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
    - name: 'Checkout repository and submodules'
      uses: actions/checkout@v2
      with:
        submodules: true
        token: ${{ secrets.ACCESS_TOKEN }}
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        registry-url: 'https://registry.npmjs.org'
    - run: |
        npm install --ignore-scripts
        npm rebuild
        npm run build --if-present
        npm test
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
  publish:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
          registry-url: https://registry.npmjs.org/
      - run: | 
          git config --global user.email "${{secrets.GIT_USER_EMAIL}}"
          git config --global user.name "${{secrets.GIT_USER_NAME}}"
          BRANCH=$(git rev-parse --abbrev-ref HEAD)
          [[ $BRANCH = 'master' ]] && RELEASE="patch" || RELEASE="prerelease --preid=rc"
          npm version $RELEASE
          echo "Pushing to $BRANCH"
          git push origin $BRANCH
          git push origin $BRANCH --tags
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
